# -*- coding: utf-8 -*-
"""Exception Handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_hD1R2vnCmubmUtQfuDEZmu-nzvl7TQ

[To read the exceptions](https://docs.python.org/3/library/exceptions.html)
"""



10/0
print("hello my name is mohit")

try:
  print(10/0)

except:
  print("error detected")

print("hello my name is mohit")

sum("1",1)

try:
  x = int(input())

  y = int(input())
  print(x/z)
except (ValueError, TypeError, NameError) as e :
  #print("Entered value is not an integer")
  print(e)
except Exception as e:
  print(e)
else:
  print("there is no exception in our code")

finally:
  print("I will always run")

print("hello my name is mohit")

ws123abc = 123

for i in range(5):
  print(i)
  break
else:
  print("hello")

